name: ğŸš§ github action meta
on: [push, pull_request]

jobs:
  asset:
    name: ğŸšš Asset download and host upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ğŸ”¨ Node Build release Theme file
      uses: actions/setup-node@v2
      with:
        node-vsersion: '16.x'
    - run: cd Theme && yarn install
    - run: cd Theme && yarn test
    - name: if fail
      uses: actions/github-script@v4
      with:
        script: |
          const ref = "${{github.ref}}";
          const pull_number = Number(ref.split("/")[2]);
          await github.pulls.createReview({
            ...context.repo,
            pull_number,
            body: "í…ŒìŠ¤íŠ¸ ì½”ë“œë¥¼ ë‹¤ì‹œ í™•ì¸í•´ì£¼ì„¸ìš”.",
            evnet: "REQUEST_CHANGES"
          });
          await github.pulls.update({
            ...context.repo,
            pull_number,
            state: "closed"
          })
          await github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Welcome, new contributor!'
          })
#       if: failure()
