name: ğŸš§ github action meta
on: [push, pull_request]

jobs:
  asset:
    name: ğŸšš Asset download and host upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ğŸ— setup-node
      uses: actions/setup-node@v2
      with:
        node-vsersion: '16.x'
    - name: ğŸ”¨ Node Build release Theme file
      id: test
      run: |
        cd Theme;\
        yarn install;\
        echo "::set-output name=JS::$(yarn lint:js)";\
        echo "::set-output name=CSS::$(yarn lint:css)";\
        yarn test;
    - name: if fail
      uses: actions/github-script@v4
      env:
        JS_LOG: ${{steps.test.outputs.JS}}
        CSS_LOG: ${{steps.test.outputs.CSS}}
      with:
        script: |
          const { JS_LOG, CSS_LOG } = process.env
          const ref = "${{github.ref}}"
          const pull_number = Number(ref.split("/")[2])
          console.log(JS_LOG, CSS_LOG)
      if: failure()
