name: ğŸš§ github action meta
on: [push, pull_request]

jobs:
  asset:
    name: ğŸšš Asset download and host upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ğŸ”¨ Node Build release Theme file
      uses: actions/setup-node@v2
      with:
        node-vsersion: '16.x'
        cache: 'yarn'
    - run: cd Theme && yarn install
    - run: cd Theme && yarn test
    - name: if fail
      uses: actions/github-script@v4
      with:
        github-token: ${{secrets.token}}
        script: |
          const ref = "${{secrets.token}}";
          const pull_number = Number(ref.split("/")[2]);
          await github.pulls.createRevier({
            ...context.repo,
            pull_number,
            body: "í…ŒìŠ¤íŠ¸ì½”ë“œë¥¼ ë‹¤ì‹œ í™•ì¸í•´ì£¼ì„¸ìš”. ",
            event: "REQUEST_CHANGES"
          })
          await github.pulls.update({
            ...context.repo,
            pull_number,
            state: "closed"
          })
      if: failure()
