name: ğŸš§ github action meta
on: [pull_request]

jobs:
  asset:
    name: ğŸšš Asset download and host upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: |
        cd Theme;
        echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: ğŸ— setup-node
      uses: actions/setup-node@v2
      with:
        node-vsersion: '16.x'
    - name: ğŸ”¨ Node Build release Theme file
      id: test
      run: |
        cd Theme
        yarn install
        CSS_LOG=$(yarn lint:css)
        CSS_LOG="${MY_STRING//'%'/'%25'}"
        CSS_LOG="${MY_STRING//$'\n'/'%0A'}"
        CSS_LOG="${MY_STRING//$'\r'/'%0D'}"
        echo "::set-output name=CSS_LOG::$CSS_LOG";
        yarn test;
    - name: if fail
      uses: actions/github-script@v4
      env:
        CSS_LOG: ${{steps.test.outputs.CSS_LOG}}
      with:
        script: |
          const { CSS_LOG } = process.env
          const ref = "${{github.ref}}"
          const pull_number = Number(ref.split("/")[2])
          await github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: CSS_LOG
          })
      if: failure()
