name: ğŸš§ github action meta
on: [pull_request]

jobs:
  asset:
    name: ğŸšš Asset download and host upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ğŸ— setup-node
      uses: actions/setup-node@v2
      with:
        node-vsersion: '16.x'
    - name: ğŸ”¨ Node Build release Theme file
      id: test
      run: |
        cd Theme;
        yarn install;
        echo '<<EOF' >> $LOG
        yarn test >> $LOG
        echo 'EOF' >> $LOG
        echo "::set-output name=LOG::$LOG";
        yarn test;
    - name: if fail
      uses: actions/github-script@v4
      env:
        LOG: ${{steps.test.outputs.LOG}}
      with:
        script: |
          const { LOG } = process.env
          const ref = "${{github.ref}}"
          const pull_number = Number(ref.split("/")[2])
          await github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: LOG
          })
      if: failure()
